spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codenames?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ChatApp2019!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    com.progmasters: info
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
cors-policies: http://localhost:4200