spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codenames?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: CallbackCats

cors-policies: http://35.158.134.255, https://35.158.134.255,