export const config = {
    HIDE_PLAYER_PATH: "/player/hidePlayer",
    CREATE_GAME_PATH: "/game/createGame",
    LOBBY_SUBSCRIPTION_PATH: "/lobby/",
    GAME_STATE_UPDATE_PATH: "/game/processVote",
    CHAT_SUBSCRIPTION_PATH: "/chat/",
    CHAT_SEND_MSG_PATH: "/chat/public",
    LOBBY_ROLE_PATH: "/lobby/role",
    LOBBY_SIDE_PATH: "/lobby/side",
    LOBBY_REFRESH_PATH: "/lobby/refresh",
    LOBBY_CREATE_PLAYER_PATH: "/lobby/create",
    LOBBY_REMOVE_BY_VOTE_PATH: "/lobby/removeByVote",
    LOBBY_REMOVE_BY_OWNER_PATH: "/lobby/removeByOwner",
    LOBBY_KICK_SUBSCRIPTION_PATH: "/kick",
    PLAYER_SUBSCRIPTION_PATH: "/player/",
    PLAYER_FETCH_PATH: "/player/getPlayer",
    PLAYER_INIT_KICK_PATH: "/player/kickInit",
    PLAYER_KICK_PATH: "/player/kick",
    PLAYER_COUNT_KICKS_PATH: "/player/kickCount",
    PLAYER_SET_READY_PATH: "/player/rdy",
    PLAYER_ROLE_SELECTION_PATH: "/player/selection",

}